sudo: required
language: python

services:
  - docker

install:
  - pip install -r tests/python-requirements.txt

script:
  - molecule test

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
