---
- hosts: all
  tasks:

  - name: omero | print ansible version
    debug:
        msg: "Ansible version: {{ ansible_version }}"
    always_run: True

  - name: omero | venv is broken on ansible 2.2
    fail: msg="This playbook does not work on Ansible 2.2 or greater."
    when: ansible_version.major ==  2 and ansible_version.minor >= 2
    always_run: True

- hosts: all
  roles:
    - role: ansible-role-omero-server
      postgresql_users_databases:
      - user: omero
        password: omero
        databases: [omero]
      omero_systemd_setup: True
      omero_server_systemd_require_network: False
      omero_system_managedrepo_group: importer
