---
- hosts: all
  roles:
    - role: ansible-role-omero-server
      postgresql_users_databases:
      - user: omero
        password: omero
        databases: [omero]
      omero_systemd_setup: True
      omero_server_systemd_require_network: False
