---
# tasks for omero-server

- include: omero-user.yml

- include: omero-datadir.yml

- include: omero-configfiles.yml

- include: omero-install.yml

- include: omero-systemd.yml
  when: omero_systemd_setup
