---
# omero system user

- name: omero server | create system user
  become: yes
  user:
    name: "{{ omero_server_system_user }}"
    home: "{{ omero_server_basedir }}"
    createhome: no
    state: present
    system: yes
    uid: "{{ omero_system_uid | default(omit) }}"

# TODO: Ideally everything should be read-only apart from the var directory
- name: omero server | create omero directories
  become: yes
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ omero_server_system_user }}"
  with_items:
    - "{{ omero_server_basedir }}"
    - "{{ omero_server_basedir }}/config"

- name: omero server | create managedrepo system group
  become: yes
  group:
    name: "{{ omero_server_system_managedrepo_group }}"
    state: present
