---
# Handlers

- name: reload systemd
  become: yes
  command: systemctl daemon-reload

- name: restart omero
  become: yes
  service:
    name: omero
    state: restarted

- name: restart omero-web
  become: yes
  service:
    name: omero-web
    state: restarted

- name: restart nginx
  become: yes
  service:
    name: nginx
    state: restarted
